/// @types index.d.ts file was autogenerated and can be modified
import config from '../../config';
import axios from 'axios';

export interface CreateFileRequestArgs {
    title: string;
    destination: string;
    deadline: string;
    open: boolean;
    description: string;    
}

async function createFile(args: CreateFileRequestArgs): Promise<any> {
    const urlPath = JSON.stringify({
        path: `${args.destination}/${args.title}`,
        autorename: true,
    });
    const bodyFile:string = JSON.stringify({
        name: args.title,
        deadline: args.deadline,
        open: args.open,
        description: args.description,
    });

    const createConfig = {
        method: 'POST',
        url: 'https://api.dropboxapi.com/2/file_requests/create',
        headers: {
            Authorization: `Bearer ${config.accessToken}`,
            'Content-Type': 'application/json',
        },
        body: {
            path: urlPath,
            data: bodyFile,
        }
    };

    const response = await axios(createConfig);
    const data = response.data;
    return data;
}

export default createFile;